package com.spring.boot.example.security.dao;

import com.spring.boot.example.security.model.MidRolePermission;
import com.spring.boot.example.security.model.MidRolePermissionExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MidRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mid_role_permission
     *
     * @mbg.generated
     */
    long countByExample(MidRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mid_role_permission
     *
     * @mbg.generated
     */
    int deleteByExample(MidRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mid_role_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mid_role_permission
     *
     * @mbg.generated
     */
    int insert(MidRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mid_role_permission
     *
     * @mbg.generated
     */
    int insertSelective(MidRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mid_role_permission
     *
     * @mbg.generated
     */
    List<MidRolePermission> selectByExample(MidRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mid_role_permission
     *
     * @mbg.generated
     */
    MidRolePermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mid_role_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MidRolePermission record, @Param("example") MidRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mid_role_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MidRolePermission record, @Param("example") MidRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mid_role_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MidRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mid_role_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MidRolePermission record);
}